### ISSUE TITLE
Script crashes when pressing joystick

### ISSUE THREAD

**Issue by klundry** [gsteenss/PijamaClock#1]
When pressing the joystick to try to get the temperature the script crashes.
This is the error:
```
Traceback (most recent call last):
  File "PijamaClock.py", line 155, in <module>
    digit=Image.open(str(temp)+".png")
  File "/usr/lib/python2.7/dist-packages/PIL/Image.py", line 2312, in open
    fp = builtins.open(filename, "rb")
IOError: [Errno 2] No such file or directory: '-371.png'
```

**Comment by gsteenss** [comment]
I hope this fixed the issue, if not let me know.

**Comment by klundry** [comment]
It does fix the script so it doesn't crash.  I can't get a temp reading though. I think there is something wrong with my sense hat temp sensor.
